services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
    restart: always
    ports:
      - 3030:3000

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
    restart: always
    ports:
      - 3031:3001
