services:
  traefik:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infra/traefik/letsencrypt:/letsencrypt
      - ./infra/traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro
    labels:
      - "traefik.http.routers.traefik-dashboard.entrypoints=web"
      - "traefik.http.routers.traefik-dashboard.tls=false"
      - "traefik.docker.network=gateway"
    networks:
      - proxy-only
      - gateway

  pgadmin:
    build: ./infra/pgadmin
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    healthcheck:
      test:
        ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    labels:
      - "traefik.enable=false"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - admin

  web:
    tty: true
    stdin_open: true
    image: ${WEB_IMAGE:-lighthouse-web:latest-dev}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      - WATCHPACK_POLLING=true
    labels:
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.routers.web.tls=false"
      - "traefik.http.routers.web.middlewares="
      - "traefik.docker.network=gateway"
    networks:
      - gateway

  api:
    tty: true
    stdin_open: true
    image: ${API_IMAGE:-lighthouse-api:latest-dev}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      - WATCHPACK_POLLING=true
    labels:
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.tls=false"
      - "traefik.http.routers.api.middlewares=api-strip"
      - "traefik.docker.network=gateway"
    networks:
      - gateway
      - backend

  postgres:
    networks:
      - backend
      - admin

networks:
  proxy-only:
    name: proxy-only
    driver: bridge
  gateway:
    name: gateway
    driver: bridge
  backend:
    name: backend
    driver: bridge
    internal: true
  admin:
    name: admin
    driver: bridge
