services:
  web:
    # No target here, inherited from base but used with NODE_ENV=development
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    environment:
      - WATCHPACK_POLLING=true

  api:
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/api/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
