name: User Story
description: Créer une nouvelle User Story
title: "US"
body:
  - type: markdown
    attributes:
      value: |
        Remplis ce formulaire pour décrire la User Story.

  - type: textarea
    id: description
    attributes:
      label: 1. Description de la User Story
      description: Décris ce que l'utilisateur souhaite accomplir.
      placeholder: "Ex: En tant qu'utilisateur, je veux pouvoir réinitialiser mon mot de passe pour accéder à mon compte en cas d'oubli."
    validations:
      required: true

  - type: textarea
    id: maquette
    attributes:
      label: 2. Maquette (optionnel)
      description: Ajoute un lien vers une maquette (Figma, Adobe XD, etc.) ou une description visuelle.
      placeholder: "Ex: Lien vers la maquette Figma : [lien]"

  - type: textarea
    id: criteres-acceptation
    attributes:
      label: 3. Critères d'acceptation
      description: Liste les conditions à remplir pour que la User Story soit considérée comme terminée.
      placeholder: |
        - [ ] L'utilisateur peut cliquer sur "Mot de passe oublié" depuis la page de connexion.
        - [ ] Un email de réinitialisation est envoyé à l'adresse associée au compte.
        - [ ] Le mot de passe peut être réinitialisé via un lien sécurisé.
    validations:
      required: true

  - type: textarea
    id: infos-tech
    attributes:
      label: 4. Infos techniques et liens (optionnel)
      description: Infos utiles à la réalisation de l'US

  - type: textarea
    id: liste-tt
    attributes:
      label: 5. Liste tâches techniques (optionnel)
      description: Liste des taches techniques à réaliser pour l'US (si l'US est petite)
