all:
  hosts:
    vps:
      ansible_host: "{{ lookup('env', 'VPS_IP') }}"
      ansible_user: "{{ remote_user | default('deploy') }}"
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_python_interpreter: /usr/bin/python3
