#!/usr/bin/env sh

if pnpm commitlint --edit "$1" > /dev/null 2>&1; then
  echo "✅ Commit message format - OK\n"
else
  echo "❌ Commit message format - KO\n"
  pnpm commitlint --edit "$1"
  exit 1
fi
